CREATE DATABASE IF NOT EXISTS feesdb;
USE feesdb;

CREATE TABLE IF NOT EXISTS students (
 id INT AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(100),
 course VARCHAR(100),
 total_fee DECIMAL(10,2),
 paid DECIMAL(10,2) DEFAULT 0.00
);

CREATE TABLE IF NOT EXISTS payments (
 id INT AUTO_INCREMENT PRIMARY KEY,
 student_id INT,
 amount DECIMAL(10,2),
 method VARCHAR(50),
 pay_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(student_id) REFERENCES students(id) ON DELETE CASCADE
);
